### PR TITLE
Fix grammar for template task

### PR DESCRIPTION
**Pull request by lepture**
Fix template task syntax. The old one doesn't work well now.

### CODE REVIEW

**Comment by soupdiver** [comment]
What's the problem with the `:` syntax? Why does it not work *well*?

**Comment by lepture** [comment]
@soupdiver I don't know. It just doesn't work. But the `=` works.

**Comment by soupdiver** [comment]
Tested with current `master`

```
ansible --version
ansible 1.9.4
  configured module search path = None
```
```
vagrant up
Bringing machine 'anxs' up with 'virtualbox' provider...
==> anxs: Importing base box 'ubuntu/trusty64'...
==> anxs: Matching MAC address for NAT networking...
==> anxs: Checking if box 'ubuntu/trusty64' is up to date...
==> anxs: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> anxs: have version '20151105.0.0'. The latest is version '20160119.0.0'. Run
==> anxs: `vagrant box update` to update.
==> anxs: Setting the name of the VM: mysql_anxs_1453381327042_77836
==> anxs: Clearing any previously set forwarded ports...
==> anxs: Fixed port collision for 22 => 2222. Now on port 2200.
==> anxs: Clearing any previously set network interfaces...
==> anxs: Preparing network interfaces based on configuration...
    anxs: Adapter 1: nat
    anxs: Adapter 2: hostonly
==> anxs: Forwarding ports...
    anxs: 22 (guest) => 2200 (host) (adapter 1)
==> anxs: Booting VM...
==> anxs: Waiting for machine to boot. This may take a few minutes...
    anxs: SSH address: 127.0.0.1:2200
    anxs: SSH username: vagrant
    anxs: SSH auth method: private key
    anxs:
    anxs: Vagrant insecure key detected. Vagrant will automatically replace
    anxs: this with a newly generated keypair for better security.
    anxs:
    anxs: Inserting generated public key within guest...
    anxs: Removing insecure key from the guest if it's present...
    anxs: Key inserted! Disconnecting and reconnecting using new SSH key...
==> anxs: Machine booted and ready!
==> anxs: Checking for guest additions in VM...
    anxs: The guest additions on this VM do not match the installed version of
    anxs: VirtualBox! In most cases this is fine, but in rare cases it can
    anxs: prevent things such as shared folders from working properly. If you see
    anxs: shared folder errors, please make sure the guest additions within the
    anxs: virtual machine match the version of VirtualBox you have installed on
    anxs: your host and reload your VM.
    anxs:
    anxs: Guest Additions Version: 4.3.10
    anxs: VirtualBox Version: 5.0
==> anxs: Setting hostname...
==> anxs: Configuring and enabling network interfaces...
==> anxs: Mounting shared folders...
    anxs: /vagrant => /Volumes/Projects/mysql
==> anxs: Running provisioner: ansible...
    anxs: Running ansible-playbook...

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [anxs.local]

TASK: [mysql | MySQL | Load the os specific variables] ************************
ok: [anxs.local]

TASK: [mysql | MySQL | Add APT repository] ************************************
skipping: [anxs.local]

TASK: [mysql | MySQL | Make sure the MySQL packages are installed] ************
changed: [anxs.local] => (item=mysql-server,mysql-client,python-mysqldb)

TASK: [mysql | MySQL | Ensure MySQL is running] *******************************
ok: [anxs.local]

TASK: [mysql | MySQL | Update the my.cnf] *************************************
changed: [anxs.local]

TASK: [mysql | MySQL | Test whether the root password has already been changed (external hostname).] ***
failed: [anxs.local] => (item=anxs) => {"failed": true, "item": "anxs"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
...ignoring
failed: [anxs.local] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
...ignoring
failed: [anxs.local] => (item=::1) => {"failed": true, "item": "::1"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
...ignoring
failed: [anxs.local] => (item=localhost) => {"failed": true, "item": "localhost"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
...ignoring

TASK: [mysql | MySQL | Changing the root password (external hostname).] *******
changed: [anxs.local] => (item=anxs)
changed: [anxs.local] => (item=127.0.0.1)
changed: [anxs.local] => (item=::1)
changed: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Test whether the root password has already been changed (local hostname).] ***
skipping: [anxs.local] => (item=127.0.0.1)
skipping: [anxs.local] => (item=::1)
skipping: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Changing the root password (local hostname).] **********
skipping: [anxs.local] => (item=127.0.0.1)
skipping: [anxs.local] => (item=::1)
skipping: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Configure MySql for easy access as root user] **********
changed: [anxs.local]

TASK: [mysql | MySQL | Remove anonymous MySQL server user] ********************
ok: [anxs.local] => (item=anxs)
ok: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Remove the MySQL test database] ************************
ok: [anxs.local]

TASK: [mysql | MySQL | Make sure the MySQL databases are present] *************
skipping: [anxs.local]

TASK: [mysql | MySQL | Make sure the MySQL users are present] *****************
skipping: [anxs.local]

TASK: [mysql | MySQL | (Monit) Copy the mysql monit service file] *************
skipping: [anxs.local]

NOTIFIED: [mysql | restart mysql] *********************************************
changed: [anxs.local]

PLAY RECAP ********************************************************************
anxs.local                 : ok=13   changed=5    unreachable=0    failed=0
```


Please provide more information about your setup because I can't reproduce

**Comment by lepture** [comment]
@soupdiver my `vagrant up` works well. But `vagrant provision` doesn't work.

> ansible 1.8.2

**Comment by soupdiver** [comment]
Still unable to reproduce
```
vagrant provision
==> anxs: Running provisioner: ansible...
    anxs: Running ansible-playbook...

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [anxs.local]

TASK: [mysql | MySQL | Load the os specific variables] ************************
ok: [anxs.local]

TASK: [mysql | MySQL | Add APT repository] ************************************
skipping: [anxs.local]

TASK: [mysql | MySQL | Make sure the MySQL packages are installed] ************
ok: [anxs.local] => (item=mysql-server,mysql-client,python-mysqldb)

TASK: [mysql | MySQL | Ensure MySQL is running] *******************************
ok: [anxs.local]

TASK: [mysql | MySQL | Update the my.cnf] *************************************
ok: [anxs.local]

TASK: [mysql | MySQL | Test whether the root password has already been changed (external hostname).] ***
ok: [anxs.local] => (item=anxs)
ok: [anxs.local] => (item=127.0.0.1)
ok: [anxs.local] => (item=::1)
ok: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Changing the root password (external hostname).] *******
skipping: [anxs.local] => (item=anxs)
skipping: [anxs.local] => (item=127.0.0.1)
skipping: [anxs.local] => (item=::1)
skipping: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Test whether the root password has already been changed (local hostname).] ***
skipping: [anxs.local] => (item=127.0.0.1)
skipping: [anxs.local] => (item=::1)
skipping: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Changing the root password (local hostname).] **********
skipping: [anxs.local] => (item=127.0.0.1)
skipping: [anxs.local] => (item=::1)
skipping: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Configure MySql for easy access as root user] **********
ok: [anxs.local]

TASK: [mysql | MySQL | Remove anonymous MySQL server user] ********************
ok: [anxs.local] => (item=anxs)
ok: [anxs.local] => (item=localhost)

TASK: [mysql | MySQL | Remove the MySQL test database] ************************
ok: [anxs.local]

TASK: [mysql | MySQL | Make sure the MySQL databases are present] *************
skipping: [anxs.local]

TASK: [mysql | MySQL | Make sure the MySQL users are present] *****************
skipping: [anxs.local]

TASK: [mysql | MySQL | (Monit) Copy the mysql monit service file] *************
skipping: [anxs.local]

PLAY RECAP ********************************************************************
anxs.local                 : ok=12   changed=0    unreachable=0    failed=0
```

**Comment by lepture** [comment]
```
TASK: [ANXS.mysql | MySQL | Update the my.cnf] ********************************
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/lepture/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/lepture/workspace/xtjp/ansible-lelouch/.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1453386470.88-112232842829962 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1453386470.88-112232842829962 && echo $HOME/.ansible/tmp/ansible-tmp-1453386470.88-112232842829962'
<127.0.0.1> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/lepture/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/lepture/workspace/xtjp/ansible-lelouch/.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=aiwqffurbwonbznyfcjibmhxbzppjphp] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-aiwqffurbwonbznyfcjibmhxbzppjphp; rc=flag; [ -r "/etc/mysql/my.cnf" ] || rc=2; [ -f "/etc/mysql/my.cnf" ] || rc=1; [ -d "/etc/mysql/my.cnf" ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc} /etc/mysql/my.cnf" && exit 0; (python -c '"'"'"'"'"'"'"'"'import hashlib; print(hashlib.sha1(open("/etc/mysql/my.cnf", "rb").read()).hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (python -c '"'"'"'"'"'"'"'"'import sha; print(sha.sha(open("/etc/mysql/my.cnf", "rb").read()).hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo "0 /etc/mysql/my.cnf")'"'"''
<127.0.0.1> PUT /tmp/tmpgGd4TT TO /home/vagrant/.ansible/tmp/ansible-tmp-1453386470.88-112232842829962/file
<127.0.0.1> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/lepture/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/lepture/workspace/xtjp/ansible-lelouch/.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=uprjcrxpjzivoodcsodnbgeeqevmzeyk] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-uprjcrxpjzivoodcsodnbgeeqevmzeyk; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1453386470.88-112232842829962/file; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1453386470.88-112232842829962/ >/dev/null 2>&1'"'"''
failed: [default] => {"failed": true, "gid": 0, "group": "root", "mode": "0777", "owner": "root", "path": "/etc/mysql/my.cnf", "size": 24, "src": "etc_mysql_my.cnf.j2", "state": "link", "uid": 0}
msg: src file does not exist, use "force=yes" if you really want to create the link: /etc/mysql/etc_mysql_my.cnf.j2

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/lepture/local.retry

default                    : ok=5    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by lepture** [comment]
@soupdiver Maybe it is because I am using *ansible 1.8.2*

**Comment by soupdiver** [comment]
Yeah that could be possible. Any reason why you stay on 1.8?

**Comment by lepture** [comment]
@soupdiver 1.9.4 works.

**Pull request closed without merging**
